parameters:
#    algorithlm_security.example.class: Algorithlm\SecurityBundle\Example

services:
#    algorithlm_security.example:
#        class: %algorithlm_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
