<?php

namespace Algorithm\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function getDashboardAccounts()
    {
        $em = $this->_em->createQueryBuilder();
        
        $em->select('a')
           ->from('AlgorithmManagerBundle:Account', 'a')
           ->setMaxResults(5)
        ;
        
        return $em->getQuery()->getResult();
    }
    
    public function getSearchAccounts($search)
    {
        $em = $this->_em->createQueryBuilder();
        
        $em->select('a')
           ->from('AlgorithmManagerBundle:Account', 'a')
           ->where('a.search LIKE :param')
           ->setParameter('param', "%$search%")
        ;
        
        return $em->getQuery()->getResult();
    }
}
