<?php

namespace Algorithm\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApacheLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApacheLogsRepository extends EntityRepository
{
    public function getApacheLogs($server)
    {
        $em = $this->_em->createQueryBuilder();
        
        $em->select('a')
           ->from('AlgorithmManagerBundle:ApacheLogs', 'a')
           ->where('a.server = :server')
           ->setParameter('server', $server)
           ->orderBy('a.id', 'DESC')
        ;
        
        return $em->getQuery()->getResult();
    }
}
