<?php

namespace Algorithm\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getByTask($task)
    {
        $em = $this->_em->createQueryBuilder();
        
        $em->select('c')
           ->from('AlgorithmManagerBundle:Comment', 'c')
           ->where('c.task = :id')
           ->setParameter('id', $task)
        ;
        
        return $em->getQuery()->getResult();
    }
}
