<?php

namespace Algorithm\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IPRepository extends EntityRepository
{
    public function getIPAuthodrized($user)
    {
        $em = $this->_em->createQueryBuilder();
        
        $em->select('i')
           ->from('AlgorithmManagerBundle:Ip', 'i')
           ->where('i.user = :user')
           ->setParameter('user', $user)
        ;
        
        return $em->getQuery()->getResult();
    }
}
