<?php

namespace Algorithm\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function getDetails($id)
    {
        $em = $this->_em->createQueryBuilder();
        
        $em->select('t, c, p, h')
           ->from('AlgorithmManagerBundle:Task', 't')
           ->leftJoin('t.comments', 'c')
           ->leftJoin('t.project', 'p')
           ->leftJoin('t.historys', 'h')
           ->where('t.id = :id')
           ->setParameter('id', $id)
        ;
        
        return $em->getQuery()->getSingleResult();
    }   
}
