<?php

namespace Algorithm\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VirtualHostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getDashboardUsers()
    {
        $em = $this->_em->createQueryBuilder();
        
        $em->select('u')
           ->from('AlgorithmManagerBundle:User', 'u')
           ->setMaxResults(5)
        ;
        
        return $em->getQuery()->getResult();
    }
    
    public function getSearchUsers($search)
    {
        $em = $this->_em->createQueryBuilder();
        
        $em->select('u')
           ->from('AlgorithmManagerBundle:User', 'u')
           ->where('u.search LIKE :param')
           ->setParameter('param', "%$search%")
        ;
        
        return $em->getQuery()->getResult();
    }
}
