security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        Algorithm\ManagerBundle\Entity\User : 
          algorithm: sha512
          encode-as-base64: true
          iterations: 10

    role_hierarchy:
        ROLE_VIEWER:      ROLE_VIEWER
        ROLE_PROJECT:     ROLE_PROJECT
        ROLE_ADMIN:       [ROLE_ADMIN, ROLE_VIEWER, ROLE_PROJECT]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_VIEWER, ROLE_PROJECT, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class:Algorithm\ManagerBundle\Entity\User, property:email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
              login_path: login
              use_forward: true
              check_path: login_check     
              post_only: true
              always_use_default_target_path: false
              default_target_path: /login
            logout:
              path: logout
              target: /login

    access_control:
        - { path: ^/access, roles: [ROLE_VIEWER, ROLE_PROJECT]  }
        - { path: ^/access/projects, roles: ROLE_PROJECT  }
        - { path: ^/access/task, roles: ROLE_PROJECT  }
